---
title: "EDA Genome Positions"
author: "Nate Olson"
date: "09/29/2014"
output: html_document
---

```{r libraries, echo = F, message=FALSE,warning=FALSE}
#packages
library(data.table)
library(plyr)
library(stringr)
library(dplyr)
library(reshape2)
```

### Objective
Perform initial exploratory data analysis on the genomic position quantile information.  This will require gathering and summarizing quantile values from multiple sqlite tables in the vcf_db sqlite directory.

### Approach 1
Create a new data base with the median quantiles

#### metadata table
```{r}
parse_vcf_filename <- function(vcf_filename){
  full_split <- str_split(vcf_filename,pattern = "mpileup_vcf/")[[1]]
  if(grepl("MiSeq",full_split[1])){
    sample_name <- str_split(full_split[2],"_")[[1]]
    return(c("name" = sample_name[1],"PLAT"= "MiSeq","VIAL" = str_sub(sample_name[1],2,2) , "REP" = str_sub(sample_name[1],5)))
  } else {
    vial = str_sub(full_split[2], 14,14)
    return(c("name" = str_c("PGM",vial,sep = "-"),"PLAT"= "PGM","VIAL" = vial, "REP" = 1))
  }  
}
vcf_dir_list <- list("../../data//RM8375//PGM//mpileup/mpileup_vcf/","../../data//RM8375//MiSeq//mpileup/mpileup_vcf/")
vcf_meta_df <- dlply(vcf_dir_list,parse_vcf_filename)
vcf_meta_df$tbl_name <- str_replace(string = vcf_meta_df$name ,pattern = "-",replacement = "_")
```

#### Loading sqlite db
```{r}
vcf_db <- src_sqlite("../../data/RM8375/vcf_db.sqlite3", create = T)

get_pure_quants <- function(db_tbl){
  #selects and retrieves the purity quantile values for each PGM datatable
  return(data.table(tbl(vcf_db(), db_tbl) %>% select(POS, CHROM, VIAL,REP, PLAT, PUR_Q2.5, PUR_Q50, PUR_Q97.5))
}

#will need to exclude undetermined
quant_tbl <- alply(vcf_meta_df$tbl_name,.fun = get_pure_quants) %>% rbind_all() 




#think about returning a list of tbl objects and used rbind_all to create a single table
start with list of sql tables
  create list of table with parameters of interest (PUR_Q50, POS, CHROM, PLAT, VIAL, REP)
    rbind_all
calculate summaries by CHROM POS and PLAT
additional figures

laply

for(table in vcf_meta_df$tbl_name){
  return(tbl(vcf_db(), pgm_table) %>% select(POS, CHROM, VIAL,REP, PLAT, PUR_Q2.5, PUR_Q50, PUR_Q97.5))
} 


```

